name: 'sops-decrypt'
description: 'Decrypt the given sops encrypted file'
inputs:
  version:
    description: 'Version of SOPS to be used'
    required: true
  file:
    description: 'SOPS encrypted file to decrypt'
    required: true
  gpg_key:
    description: 'GPG key to decrypt the file'
    required: true
  output_type:
    description: 'Output format of the decrypted data'
    default: 'json'
outputs:
  data:
    description: 'Decrypted data in JSON'
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/post-action/index.js'
